-- USER SQL
ALTER USER "CODERLINK_DIV"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "CODERLINK_DIV" QUOTA UNLIMITED ON USERS;

-- ROLES

-- SYSTEM PRIVILEGES
GRANT create session TO CODERLINK_DIV;
GRANT create table TO CODERLINK_DIV;
GRANT create view TO CODERLINK_DIV;
GRANT create any trigger TO CODERLINK_DIV;
GRANT create any procedure TO CODERLINK_DIV;
GRANT create sequence TO CODERLINK_DIV;
GRANT create synonym TO CODERLINK_DIV;
