

INSERT INTO CODERLINK_DIV.CARS
(MARK, MODEL, GOVERNMENT_NUMBER, CAR_TYPE)
VALUES ('Газель', 'Соболь', 'А00АА152', 'Тип');

INSERT INTO CODERLINK_DIV.CARS
(MARK, MODEL, GOVERNMENT_NUMBER, CAR_TYPE)
VALUES ('Газель', 'Соболь', 'А00АА150', 'Тип');