INSERT INTO CODERLINK_DIV.JOURNAL_OF_ACCOUNTING
(FIO_DECLARANT, CAR_ID, DRIVER_ID, DESTINATION_POINT_SENDING_ID, DESTINATION_POINT_ARRIVAL_ID, DEPARTURE_TIME, ARRIVAL_TIME, STATUS_ID, COMMENTS)
VALUES('Сидоров', 21, 21, 3, 2, sysdate, sysdate, 1, '');

INSERT INTO CODERLINK_DIV.JOURNAL_OF_ACCOUNTING
(FIO_DECLARANT, CAR_ID, DRIVER_ID, DESTINATION_POINT_SENDING_ID, DESTINATION_POINT_ARRIVAL_ID, DEPARTURE_TIME, ARRIVAL_TIME, STATUS_ID, COMMENTS)
VALUES('Сидоров', 21, 21, 3, 2, sysdate, sysdate+100, 1, '');
