INSERT INTO CODERLINK_DIV.DESTINATION_POINT
(TEXT) VALUES( 'Точка 1');


INSERT INTO CODERLINK_DIV.DESTINATION_POINT
(TEXT) VALUES( 'Точка 2');

INSERT INTO CODERLINK_DIV.DESTINATION_POINT
(TEXT) VALUES( 'Точка 3');

INSERT INTO CODERLINK_DIV.DESTINATION_POINT
(TEXT) VALUES( 'Точка 4');
